from typing import Dict

# WIN_CURSORS_CFG: Dict[str, str] = {
#     "Alternate": "right_ptr" ,
#     "Cross": "cross" ,
#     "Default": "left_ptr" ,
#     "pointer": "left_ptr" ,
#     "pointer": "copy" ,
#     "Diagonal_1": "bottom_right_corner" ,
#     "dgn1": "bottom_right_corner" ,
#     "Diagonal_2": "bottom_left_corner" ,
#     "Dgn2": "bottom_left_corner" ,
#     "Handwriting": "pencil" ,
#     "Help": "question_arrow" ,
#     "Horizontal": "sb_h_double_arrow" ,
#     "Horizontal": "left_side" ,
#     "horz": "sb_h_double_arrow" ,
#     "horz": "sb_right_double_arrow" ,
#     "horz": "sb_left_double_arrow" ,
#     "IBeam": "xterm" ,
#     "text": "xterm" ,
#     "Link": "hand2" ,
#     "Link": "link" ,
#     "Move": "hand1" ,
#     "Move": "move" ,
#     "Move": "all-scroll" ,
#     "Move": "dotbox" ,
#     "Move": "plus" ,
#     "Unavailiable": "crossed_circle" ,
#     "unavailable": "crossed_circle" ,
#     "unavailable": "dnd_no_drop" ,
#     "unavailable": "X_cursor" ,
#     "Vertical": "sb_v_double_arrow" ,
#     "vert": "sb_v_double_arrow" ,
#     "vert": "top_side" ,
#     "vert": "sb_up_arrow" ,
#     "vert": "sb_down_arrow" ,
#     "Work": "left_ptr_watch" ,
#     "working": "left_ptr_watch" ,
#     "Busy": "wait" ,
# }

from typing import Dict, List

WIN_CURSORS_CFG: Dict[str, List[str]] = {
    "Alternate": ["right_ptr"],
    "Cross": ["cross"],
    "Default": ["left_ptr"],
    "pointer": ["left_ptr", "copy"],
    "Diagonal_1": ["bottom_right_corner"],
    "dgn1": ["bottom_right_corner"],
    "Diagonal_2": ["bottom_left_corner"],
    "Dgn2": ["bottom_left_corner"],
    "Handwriting": ["pencil"],
    "Hand": ["pencil"],
    "Help": ["question_arrow"],
    "Horizontal": ["sb_h_double_arrow", "left_side", "sb_right_arrow", "sb_left_arrow"],
    "horz": ["sb_h_double_arrow", "left_side", "sb_right_arrow", "sb_left_arrow"],
    "IBeam": ["xterm", "text"],
    "Link": ["hand2", "link"],
    "Move": ["hand1", "move", "all-scroll", "dotbox", "plus"],
    "Text": ["xterm"],
    "Unavailiable": ["crossed_circle", "dnd_no_drop", "X_cursor"],
    "unavailable": ["crossed_circle", "dnd_no_drop", "X_cursor"],
    "Vertical": ["sb_v_double_arrow", "top_side", "sb_up_arrow", "sb_down_arrow"],
    "vert": ["sb_v_double_arrow", "top_side", "sb_up_arrow", "sb_down_arrow"],
    "Work": ["left_ptr_watch"],
    "working": ["left_ptr_watch"],
    "Busy": ["wait"],
}
